### PR TITLE
Add support for NC 30

### LINKED ISSUE #200: Nextcloud 30 support
### Is your feature request related to a problem? Please describe.

Nextcloud 30 has been released, but this app doesn't currently support it.

### Describe the solution you'd like

Please add support for Nextcloud 30.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by IndrekHaav**
The app seems to work fine, this just marks it as compatible.
resolves #200

### CODE REVIEW

**Comment by IndrekHaav** [comment]
Looks like @datenangebot hasn't been active for a while. Pinging @nickvergessen, not sure who else can merge PRs...

**Comment by kenda** [comment]
Merged your PR but I think we would need a version bump + release to get this out. But I'm not familiar anymore how the release process worked in the last time here.

**Comment by nickvergessen** [comment]
> But I'm not familiar anymore how the release process worked in the last time here.

If you have the app key, it should be something like:
- Bump version in appinfo/info.xml
- Commit and push
- Create a git tag with the version from appinfo/info.xml
- Push the tag
- Make a release out of the tag https://github.com/nextcloud/health/tags
- Remove the leading `#` from those lines: https://github.com/nextcloud/health/blob/main/Makefile#L67-L70
- `make appstore-local`
- Upload the file from `build/artifacts` to the release
- Go to https://apps.nextcloud.com/developer/apps/releases/new
- Post the link to the uploaded health.tar.gz together with the "signature" output from the `make` command above

**Comment by kenda** [comment]
> If you have the app key, it should be something like:

No, I don't have the app key. The releases were always done by @datenangebot in the past afaik.

**Comment by IndrekHaav** [comment]
Does this mean the app is effectively unmaintained? Considering the only person who can make a new release appears to be inactive.

**Comment by nickvergessen** [comment]
You can request a new certificate in https://github.com/nextcloud/app-certificate-requests?tab=readme-ov-file#how-to-request-an-app-certificate

**Comment by IndrekHaav** [comment]
> If I can support you to get a new sign key or if there is a handover process, let me know.

@datenangebot If you meant me, then unfortunately I have neither the time nor experience to become a NC app maintainer.

If a new version with NC 30 support is not happening, then perhaps there should be an announcement about this. As you can see from the linked issue, there are quite a few people waiting for an update.

**Comment by solonovamax** [comment]
> And there are known security problems in this app, that's why I don't feel good to ship new releases.

like what? or can you not disclose them publicly?

because if they're able to be disclosed, then it would be possible for someone else to go about fixing them

**Comment by BraidenPsiuk** [comment]
If that information can't easily be disclosed, maybe this can be answered- Is it worth spending time fixing these security problems? Or is it better to spend the time developing a new app from scratch that follows more modern practices?

And if a new app is developed, is there a good strategy for "sunsetting" old apps and replacing them with new ones?

As a user of this app for a few years now I have unfortunately felt the lack of updates and care for this app, it is almost always the last to get support when upgrading to new NC versions.

**Pull request merged**
